services:
  ollama:
    build:
      context: ./docker/
      dockerfile: Dockerfile-ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    # entrypoint: [ "/bin/sh", "-c", "ollama serve & sleep 5 && ollama run llama3" ]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      # Especifica qual modelo deve vir selecionado por padrão no chat
      - 'DEFAULT_MODELS=llama3'
    restart: unless-stopped
    depends_on:
      - ollama


volumes:
  ollama:
  open-webui: